# Generated by Django 6.0.3 on 2026-03-17 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sosalert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SOSAlert',
        ),
    ]
