# Generated by Django 6.0.3 on 2026-03-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='s3_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
