# Generated by Django 6.0.3 on 2026-03-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_inspection_image_url_inspection_s3_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='s3_key',
        ),
    ]
