# Generated by Django 6.0.3 on 2026-03-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_remove_inspection_image_url_remove_inspection_s3_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='s3_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
