# Generated by Django 6.0.3 on 2026-03-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_inspection_s3_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='s3_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
