# Generated by Django 6.0.3 on 2026-03-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_inspection_s3_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspection',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Inspection', 'verbose_name_plural': 'Inspections'},
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='ai_explanation',
        ),
        migrations.AlterField(
            model_name='humanoverride',
            name='from_date',
            field=models.DateTimeField(help_text='When the override was applied'),
        ),
        migrations.AlterField(
            model_name='humanoverride',
            name='new_classification',
            field=models.CharField(help_text="Classification after override: 'good' or 'defect'", max_length=50),
        ),
        migrations.AlterField(
            model_name='humanoverride',
            name='new_status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('human_review', 'Human Review Required')], help_text='Status after override', max_length=50),
        ),
        migrations.AlterField(
            model_name='humanoverride',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional observations or notes'),
        ),
        migrations.AlterField(
            model_name='humanoverride',
            name='original_classification',
            field=models.CharField(blank=True, help_text='AI classification before override', max_length=50),
        ),
        migrations.AlterField(
            model_name='humanoverride',
            name='original_status',
            field=models.CharField(help_text='Status before override', max_length=50),
        ),
        migrations.AlterField(
            model_name='humanoverride',
            name='overridden_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp'),
        ),
        migrations.AlterField(
            model_name='humanoverride',
            name='reason',
            field=models.TextField(help_text='Reason for overriding the AI decision'),
        ),
        migrations.AlterField(
            model_name='humanoverride',
            name='to_date',
            field=models.DateTimeField(blank=True, help_text='When override expires (if temporary, otherwise NULL)', null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='ai_classification',
            field=models.CharField(blank=True, help_text="AI classification: 'good' or 'defect'", max_length=50),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='ai_confidence',
            field=models.FloatField(blank=True, help_text='AI confidence score (0.0 to 1.0)', null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='ai_processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when AI completed processing', null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='human_override',
            field=models.BooleanField(default=False, help_text='Has a human overridden the AI decision?'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='job_id',
            field=models.UUIDField(blank=True, help_text='Job ID from AI service for tracking', null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='name',
            field=models.CharField(help_text='Original filename of the uploaded image', max_length=255),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='s3_key',
            field=models.CharField(blank=True, help_text='S3 key/path for generating presigned URLs (for private buckets)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='s3_url',
            field=models.URLField(blank=True, help_text='Direct S3 URL of the image (for public buckets)', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('human_review', 'Human Review Required')], default='queued', help_text='Current processing status', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp of upload'),
        ),
    ]
