# Generated by Django 6.0.3 on 2026-03-20 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_sosalert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emergency_contact_phone',
        ),
    ]
